# Copyright 2025, Giordano Salvador
# SPDX-License-Identifier: BSD-3-Clause

name: Fedora 41

on: 

  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      build_mode:
        description: Build optimization level 
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release

jobs:

  run:
    uses: e3m3/scan-rs/.github/workflows/build-and-test-ubuntu2404.yaml@main
    with:
      build_mode: ${{ inputs.build_mode }}
      distro: fedora
      os_ver: 41
      os: fedora-41
